<script src="../resources/libs/Modernizr/modernizr-2.6.2.js"></script>
<script src="../resources/libs/jquery/Core/jquery-3.3.1.js"></script>
<script src="../resources/libs/Popper/umd/popper.min.js"></script>
<script src="../resources/libs/bootstrap/Core/js/bootstrap.min.js"></script>
<script src="../resources/libs/Responsive/respond.min.js"></script>
<script src="../resources/libs/bootstrap/Bundle/js/bootstrap.bundle.min.js"></script>
<script src="../resources/libs/FontAwesome/js/all.min.js"></script>
<script src="../resources/libs/bootstrap/Select/js/bootstrap-select.min.js"></script>
<script src="../resources/libs/bootstrap/bootstrap4-toggle/js/bootstrap4-toggle.js"></script>
<script src="../resources/libs/jquery/Validate/jquery.validate.min.js"></script>
<script src="../resources/libs/AdminLTE/js/adminlte.min.js"></script>
<!-- <script src="../resources/libs/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script> -->
<script src="../resources/libs/SweetAlert/js/sweetalert.min.js"></script>
